# Generated by Django 5.2.17 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMaterialRequest',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=64, unique=True, verbose_name='Request / Issue Slip #')),
                ('project_id', models.CharField(blank=True, default='', max_length=64)),
                ('job_id', models.CharField(blank=True, default='', max_length=64)),
                ('job_number', models.CharField(blank=True, default='', max_length=64)),
                ('work_order_number', models.CharField(blank=True, default='', max_length=64)),
                ('bom_number', models.CharField(blank=True, default='BOM-2026-001', max_length=64)),
                ('bom_revision', models.CharField(blank=True, default='Rev-01', max_length=20)),
                ('production_stage', models.CharField(blank=True, default='Fabrication & Welding', max_length=150)),
                ('requested_by', models.CharField(blank=True, default='Production Supervisor', max_length=150)),
                ('issued_to', models.CharField(blank=True, default='', max_length=150)),
                ('issued_by', models.CharField(blank=True, default='Store Supervisor', max_length=150)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('warehouse_id', models.CharField(default='WH-001', max_length=64)),
                ('warehouse_name', models.CharField(blank=True, default='Raw Material Yard & Plate Store', max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Fully Issued', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Production Material Request & Issue',
                'verbose_name_plural': 'Production Material Requests & Store Issues',
            },
        ),
    ]
