# Generated by Django 5.2.17 on 2026-10-04 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionmaterialrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('dispatch_number', models.CharField(max_length=64, unique=True)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('job_id', models.CharField(blank=True, max_length=64)),
                ('job_number', models.CharField(blank=True, max_length=64)),
                ('work_order_number', models.CharField(blank=True, max_length=64)),
                ('finished_goods_number', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('destination_city', models.CharField(blank=True, max_length=128)),
                ('product_name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(default='Nos', max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('batch_number', models.CharField(blank=True, max_length=128)),
                ('weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transporter_name', models.CharField(blank=True, max_length=255)),
                ('vehicle_number', models.CharField(blank=True, max_length=64)),
                ('lr_number', models.CharField(blank=True, max_length=64)),
                ('driver_name', models.CharField(blank=True, max_length=128)),
                ('driver_mobile', models.CharField(blank=True, max_length=32)),
                ('e_way_bill_number', models.CharField(blank=True, max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('packaging_type', models.CharField(default='Wooden Saddle & Tarpaulin', max_length=128)),
                ('dispatch_type', models.CharField(default='Road Freight (Trailer)', max_length=64)),
                ('qc_clearance_by', models.CharField(blank=True, default='Quality Manager', max_length=128)),
                ('dispatched_by', models.CharField(blank=True, default='Dispatch Officer', max_length=128)),
                ('status', models.CharField(default='Ready for Dispatch', max_length=64)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispatch Order & Delivery Challan',
                'verbose_name_plural': 'Dispatch Orders & Delivery Challans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productionentry',
            options={'verbose_name': 'Production Entry', 'verbose_name_plural': 'Production Entries'},
        ),
        migrations.AlterModelOptions(
            name='wiprecord',
            options={'verbose_name': 'WIP Record', 'verbose_name_plural': 'WIP Records'},
        ),
    ]
