# Generated by Django 4.2.30 on 2026-10-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_dispatchorder_alter_productionentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='sales_order_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
