# Generated by Django 4.2.30 on 2026-10-08 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_dispatchorder_sales_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingOrder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('packing_number', models.CharField(max_length=64, unique=True)),
                ('packing_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('sales_order_id', models.CharField(blank=True, max_length=64)),
                ('sales_order_number', models.CharField(blank=True, max_length=64)),
                ('job_id', models.CharField(blank=True, max_length=64)),
                ('job_number', models.CharField(blank=True, max_length=64)),
                ('project_id', models.CharField(blank=True, max_length=64)),
                ('project_number', models.CharField(blank=True, max_length=64)),
                ('qc_inspection_number', models.CharField(blank=True, max_length=64)),
                ('finished_goods_number', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('packed_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uom', models.CharField(default='Nos', max_length=32)),
                ('package_type', models.CharField(default='Heavy Duty Wooden Crate', max_length=128)),
                ('package_dimensions', models.CharField(blank=True, default='', max_length=128)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packed_by', models.CharField(blank=True, default='Packing Supervisor', max_length=128)),
                ('verified_by', models.CharField(blank=True, default='Quality Inspector', max_length=128)),
                ('status', models.CharField(default='Packed', max_length=64)),
                ('items', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Packing Order',
                'verbose_name_plural': 'Packing Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
