# Generated by Django 4.2.30 on 2026-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_packingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCompletion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('completion_number', models.CharField(max_length=64, unique=True)),
                ('completion_date', models.DateField()),
                ('job_id', models.CharField(blank=True, max_length=64)),
                ('job_number', models.CharField(blank=True, max_length=64)),
                ('work_order_number', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rework_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scrap_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_by', models.CharField(blank=True, max_length=128)),
                ('qc_status', models.CharField(default='Passed', max_length=64)),
                ('remarks', models.TextField(blank=True)),
                ('hydro_test_pressure', models.CharField(blank=True, max_length=128)),
                ('hydro_holding_duration', models.CharField(blank=True, max_length=64)),
                ('hydro_test_status', models.CharField(default='Passed', max_length=64)),
                ('dp_test_joints', models.CharField(blank=True, max_length=255)),
                ('dp_test_status', models.CharField(default='Accepted', max_length=64)),
                ('dimension_report_no', models.CharField(blank=True, max_length=128)),
                ('dimension_status', models.CharField(blank=True, max_length=128)),
                ('qc_inspector_name', models.CharField(blank=True, max_length=128)),
                ('certificate_number', models.CharField(blank=True, max_length=128)),
                ('equipment_serial_number', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Production Completion & QC Clearance',
                'verbose_name_plural': 'Production Completions & QC Clearances',
                'ordering': ['-created_at'],
            },
        ),
    ]
