# Generated by Django 5.2.17 on 2026-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=64)),
                ('job_number', models.CharField(blank=True, default='', max_length=64)),
                ('document_name', models.CharField(max_length=200)),
                ('type', models.CharField(default='Drawing', max_length=50)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('related_record', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file_size', models.CharField(blank=True, default='1.5 MB', max_length=50)),
                ('file_url', models.CharField(blank=True, default='', max_length=255)),
                ('upload_date', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
