# Generated by Django 5.2.17 on 2026-09-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='actual_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='milestone_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='planned_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='target_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
