# Generated by Django 5.2.17 on 2026-09-29 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmilestone_actual_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdelay',
            name='corrective_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='delay_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='delay_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='delay_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='expected_delivery_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='original_delivery_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='status',
            field=models.CharField(default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='task_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdelay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='issue_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='issue_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='reported_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='resolution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='department',
            field=models.CharField(blank=True, default='project', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdelay',
            name='recorded_by',
            field=models.CharField(blank=True, default='Super Admin', max_length=150),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='created_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='department',
            field=models.CharField(blank=True, default='Production', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='reported_by',
            field=models.CharField(blank=True, default='Super Admin', max_length=150),
        ),
        migrations.AlterField(
            model_name='projectissue',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
