# Generated by Django 5.2.17 on 2026-09-29 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdelay_corrective_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchangerequest',
            name='approval_status',
            field=models.CharField(default='requested', max_length=30),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='approved_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='change_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='change_request_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='cost_impact',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='design_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='material_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='requested_by',
            field=models.CharField(blank=True, default='Customer Representative', max_length=150),
        ),
        migrations.AddField(
            model_name='customerchangerequest',
            name='timeline_impact_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerchangerequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customerchangerequest',
            name='request_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerchangerequest',
            name='request_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customerchangerequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
