# Generated by Django 5.2.17 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='bom_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='bom_revision',
            field=models.CharField(blank=True, default='Rev-01', max_length=20),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='issued_by',
            field=models.CharField(blank=True, default='Hitesh Rawal (Store Head)', max_length=150),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='production_stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='total_issue_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='warehouse_name',
            field=models.CharField(blank=True, default='Main Raw Material Warehouse', max_length=200),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='material_issue_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='received_by',
            field=models.CharField(blank=True, default='Hitesh Rawal (Store Head)', max_length=150),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='total_return_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='warehouse_name',
            field=models.CharField(blank=True, default='Main Raw Material Warehouse', max_length=200),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='work_order_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='batch_lot',
            field=models.CharField(blank=True, default='HEAT-98421', max_length=100),
        ),
    ]
