# Generated by Django 5.2.17 on 2026-09-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_materialissue_bom_number_materialissue_bom_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(max_length=64, unique=True)),
                ('adjustment_date', models.CharField(max_length=50)),
                ('warehouse_id', models.CharField(default='wh-main', max_length=64)),
                ('warehouse_name', models.CharField(default='Main Raw Material Warehouse', max_length=200)),
                ('location_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_id', models.CharField(blank=True, default='', max_length=64)),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=200)),
                ('system_quantity', models.FloatField(default=0)),
                ('physical_quantity', models.FloatField(default=0)),
                ('difference_quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('adjustment_value', models.FloatField(default=0)),
                ('reason', models.CharField(default='Damaged Stock', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.CharField(default='Hitesh Rawal (Store Head)', max_length=150)),
                ('status', models.CharField(default='Approved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=64, unique=True)),
                ('transfer_date', models.CharField(max_length=50)),
                ('from_warehouse_id', models.CharField(default='wh-main', max_length=64)),
                ('from_warehouse_name', models.CharField(default='Main Raw Material Warehouse', max_length=200)),
                ('from_location_code', models.CharField(blank=True, default='', max_length=100)),
                ('to_warehouse_id', models.CharField(default='wh-scrap', max_length=64)),
                ('to_warehouse_name', models.CharField(default='Scrap & Rejection Yard', max_length=200)),
                ('to_location_code', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_by', models.CharField(default='Bhavin Shah (Production Manager)', max_length=150)),
                ('approved_by', models.CharField(default='Hitesh Rawal (Store Head)', max_length=150)),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
