# Generated by Django 4.2.22 on 2026-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stockadjustment_stocktransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='scrapentry',
            options={'verbose_name': 'Scrap Entry', 'verbose_name_plural': 'Scrap Entries'},
        ),
        migrations.AlterModelOptions(
            name='stockledgerentry',
            options={'verbose_name': 'Stock Ledger Entry', 'verbose_name_plural': 'Stock Ledger Entries'},
        ),
    ]
