# Generated by Django 4.2.30 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_itemcategory_options_alter_scrapentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='delivery_challan_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='grn_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='total_received_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='transporter_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='warehouse_name',
            field=models.CharField(blank=True, default='Main Raw Material Warehouse', max_length=200),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='requested_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='work_order_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='accepted_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='lot_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='rejected_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='sample_size',
            field=models.FloatField(default=0),
        ),
    ]
