# Generated by Django 5.2.17 on 2026-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('record_number', models.CharField(max_length=64)),
                ('requester_name', models.CharField(max_length=128)),
                ('requester_role', models.CharField(blank=True, max_length=128)),
                ('request_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('related_job_number', models.CharField(blank=True, max_length=64)),
                ('remarks', models.TextField(blank=True)),
                ('urgency', models.CharField(default='Normal', max_length=32)),
                ('status', models.CharField(default='Pending', max_length=32)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ERPAlertItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=64)),
                ('severity', models.CharField(default='Info', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_required', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
