# Generated by Django 4.2.22 on 2026-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_customer360summary_employee360summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer360summary',
            options={'verbose_name': 'Customer 360 Summary', 'verbose_name_plural': 'Customer 360 Summaries'},
        ),
        migrations.AlterModelOptions(
            name='employee360summary',
            options={'verbose_name': 'Employee 360 Summary', 'verbose_name_plural': 'Employee 360 Summaries'},
        ),
        migrations.AlterModelOptions(
            name='erpreportcenteritem',
            options={'verbose_name': 'Report Center Item', 'verbose_name_plural': 'Report Center Items'},
        ),
        migrations.AlterModelOptions(
            name='executivedashboardkpi',
            options={'verbose_name': 'Executive Dashboard KPI', 'verbose_name_plural': 'Executive Dashboard KPIs'},
        ),
        migrations.AlterModelOptions(
            name='globalactivitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Global Activity Log', 'verbose_name_plural': 'Global Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='itemmaterial360summary',
            options={'verbose_name': 'Material 360 Summary', 'verbose_name_plural': 'Material 360 Summaries'},
        ),
        migrations.AlterModelOptions(
            name='job360overview',
            options={'verbose_name': 'Job 360 Overview', 'verbose_name_plural': 'Job 360 Overviews'},
        ),
        migrations.AlterModelOptions(
            name='jobprofitabilityrecord',
            options={'verbose_name': 'Job Profitability Record', 'verbose_name_plural': 'Job Profitability Records'},
        ),
        migrations.AlterModelOptions(
            name='supplier360summary',
            options={'verbose_name': 'Supplier 360 Summary', 'verbose_name_plural': 'Supplier 360 Summaries'},
        ),
    ]
