# Generated by Django 5.2.17 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Uma Techno Fab Private Limited', max_length=200)),
                ('tagline', models.CharField(default='Custom Heavy Fabrication & Make-to-Order Equipment Manufacturer', max_length=255)),
                ('logo_url', models.CharField(default='/logo.png', max_length=255)),
                ('address', models.TextField(default='Plot No. 48/B, GIDC Industrial Estate, Makarpura')),
                ('city', models.CharField(default='Vadodara', max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(default='390010', max_length=20)),
                ('phone', models.CharField(default='+91 265 2645800 / +91 98250 11223', max_length=100)),
                ('email', models.EmailField(default='info@umatechnofab.com', max_length=254)),
                ('website', models.CharField(default='https://www.umatechnofab.com', max_length=200)),
                ('gstin', models.CharField(default='24AABCU9821R1ZX', max_length=30)),
                ('pan', models.CharField(default='AABCU9821R', max_length=20)),
                ('cin', models.CharField(default='U28112GJ2012PTC071234', max_length=50)),
                ('financial_year', models.CharField(default='2026-2027', max_length=20)),
                ('currency', models.CharField(default='INR (₹)', max_length=30)),
                ('timezone', models.CharField(default='Asia/Kolkata (IST)', max_length=50)),
                ('bank_name', models.CharField(default='State Bank of India', max_length=150)),
                ('bank_account_no', models.CharField(default='30491827461', max_length=50)),
                ('bank_ifsc', models.CharField(default='SBIN0001234', max_length=30)),
                ('bank_branch', models.CharField(default='Industrial Estate Branch, Vadodara', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(default='info', max_length=50)),
                ('department', models.CharField(default='all', max_length=50)),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NumberingSetting',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('doc_type', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, default='', max_length=50)),
                ('current_number', models.IntegerField(default=1)),
                ('digit_count', models.IntegerField(default=4)),
                ('sample_preview', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
