# Generated by Django 5.2.17 on 2026-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('backup_name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(default='Full Database & Media', max_length=50)),
                ('file_size', models.CharField(default='24.5 MB', max_length=50)),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('backup_date', models.CharField(max_length=50)),
                ('file_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(default='Super Admin', max_length=150)),
                ('is_automatic', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('bug_no', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('module_page', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(default='Medium', max_length=30)),
                ('priority', models.CharField(default='Normal', max_length=30)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('assignee', models.CharField(blank=True, default='', max_length=150)),
                ('steps_to_reproduce', models.TextField(blank=True, default='')),
                ('actual_result', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('fixed_notes', models.TextField(blank=True, default='')),
                ('created_date', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
