# Generated by Django 5.2.17 on 2026-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backuprecord_bugticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=200)),
                ('records_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('imported_by', models.CharField(default='Super Admin', max_length=150)),
                ('imported_at', models.CharField(max_length=50)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoLiveChecklistItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(default='Super Admin', max_length=150)),
                ('status', models.CharField(default='Pass', max_length=30)),
                ('signoff_date', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityCheckRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Authentication & Access', max_length=100)),
                ('status', models.CharField(default='Pass', max_length=30)),
                ('severity', models.CharField(default='High', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('remediation_notes', models.TextField(blank=True, default='')),
                ('last_evaluated_at', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
