# Generated by Django 5.2.17 on 2026-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=64, unique=True)),
                ('credit_note_date', models.DateField()),
                ('customer_id', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('original_invoice_number', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(default='Price Difference / Return', max_length=255)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('status', models.CharField(default='Approved', max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-credit_note_date'],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(max_length=64, unique=True)),
                ('debit_note_date', models.DateField()),
                ('supplier_id', models.CharField(max_length=64)),
                ('supplier_name', models.CharField(max_length=255)),
                ('original_invoice_number', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(default='Goods Return / Rate Difference', max_length=255)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('status', models.CharField(default='Approved', max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-debit_note_date'],
            },
        ),
    ]
