# Generated by Django 5.2.17 on 2026-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_creditnote_debitnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(default='Current', max_length=64)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=128)),
                ('ifsc_code', models.CharField(blank=True, max_length=64)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('gl_account_code', models.CharField(blank=True, max_length=64)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContraVoucher',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('contra_number', models.CharField(max_length=64, unique=True)),
                ('contra_date', models.DateField()),
                ('contra_type', models.CharField(default='Bank_to_Bank', max_length=64)),
                ('from_account_id', models.CharField(blank=True, max_length=64)),
                ('from_account_name', models.CharField(max_length=255)),
                ('from_account_code', models.CharField(blank=True, max_length=64)),
                ('to_account_id', models.CharField(blank=True, max_length=64)),
                ('to_account_name', models.CharField(max_length=255)),
                ('to_account_code', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('reference_number', models.CharField(blank=True, max_length=128)),
                ('narration', models.TextField(blank=True)),
                ('status', models.CharField(default='Posted', max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contra_date'],
            },
        ),
    ]
