# Generated by Django 5.2.17 on 2026-09-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount_contravoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(max_length=64, unique=True)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(default='Power & Electricity', max_length=128)),
                ('claimed_by', models.CharField(blank=True, max_length=128)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('payment_mode', models.CharField(default='Bank_Transfer', max_length=64)),
                ('bank_cash_account_name', models.CharField(blank=True, max_length=128)),
                ('project_id', models.CharField(blank=True, max_length=64)),
                ('job_number', models.CharField(blank=True, max_length=64)),
                ('cost_center_code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending_Approval', max_length=64)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
