# Generated by Django 5.2.17 on 2026-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expenseentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=64, unique=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Plant & Machinery', max_length=128)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(default='Bay-3 Heavy Machine Shop', max_length=255)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('useful_life_years', models.IntegerField(default=10)),
                ('depreciation_method', models.CharField(default='WDV', max_length=32)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('current_book_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
    ]
