# Generated by Django 4.2.22 on 2026-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fixedasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Expense Entry', 'verbose_name_plural': 'Expense Entries'},
        ),
        migrations.AlterModelOptions(
            name='jobcostingsummary',
            options={'verbose_name': 'Job Costing Summary', 'verbose_name_plural': 'Job Costing Summaries'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
