# Generated by Django 4.2.22 on 2026-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='customerpo',
            options={'verbose_name': 'Customer PO', 'verbose_name_plural': 'Customer POs'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
    ]
