# Generated by Django 4.2.30 on 2026-10-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_activity_options_alter_customerpo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
