# Generated by Django 4.2.30 on 2026-10-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_salesorder_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
