# Generated by Django 4.2.30 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_quotation_approved_at_quotation_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='attachment_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpo',
            name='po_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customerpo',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerpo',
            name='sales_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='latest_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='machine_product',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='assigned_project_manager',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_value',
            field=models.FloatField(default=0),
        ),
    ]
