# Generated by Django 4.2.30 on 2026-10-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerpo_attachment_url_customerpo_po_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='contact_mobile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
