# Generated by Django 5.2.17 on 2026-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('resignation_date', models.DateField()),
                ('last_working_date', models.DateField()),
                ('notice_period_days', models.IntegerField(default=30)),
                ('reason', models.TextField(blank=True)),
                ('exit_interview_notes', models.TextField(blank=True)),
                ('department_clearance', models.BooleanField(default=False)),
                ('asset_return_clearance', models.BooleanField(default=False)),
                ('hr_clearance', models.BooleanField(default=False)),
                ('accounts_clearance', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(blank=True, max_length=64)),
                ('candidate_name', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('reporting_manager', models.CharField(blank=True, max_length=128)),
                ('shift', models.CharField(blank=True, max_length=128)),
                ('salary_structure_id', models.CharField(blank=True, max_length=64)),
                ('offered_ctc', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('onboarding_checklist', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='In Progress', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('effective_date', models.DateField()),
                ('old_designation', models.CharField(max_length=128)),
                ('new_designation', models.CharField(max_length=128)),
                ('old_grade', models.CharField(blank=True, max_length=64)),
                ('new_grade', models.CharField(blank=True, max_length=64)),
                ('old_ctc', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('new_ctc', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='Approved', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('effective_date', models.DateField()),
                ('from_department', models.CharField(max_length=128)),
                ('to_department', models.CharField(max_length=128)),
                ('from_designation', models.CharField(blank=True, max_length=128)),
                ('to_designation', models.CharField(blank=True, max_length=128)),
                ('from_location', models.CharField(blank=True, max_length=128)),
                ('to_location', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='Approved', max_length=32)),
            ],
        ),
    ]
