# Generated by Django 5.2.17 on 2026-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employeeexit_employeeonboarding_employeepromotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=128)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(default='Public Holiday', max_length=64)),
                ('applicable_departments', models.JSONField(blank=True, default=list)),
                ('is_optional', models.BooleanField(default=False)),
                ('financial_year', models.CharField(default='FY 2026-27', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['holiday_date'],
            },
        ),
    ]
