# Generated by Django 5.2.17 on 2026-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('appraisal_number', models.CharField(max_length=64, unique=True)),
                ('employee_id', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('cycle_period', models.CharField(default='FY 2025-26 Annual', max_length=128)),
                ('kpi_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('self_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('manager_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('manager_comments', models.TextField(blank=True)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('recommended_increment_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Manager Review Pending', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
