# Generated by Django 5.2.17 on 2026-09-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTask',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('design_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('project_id', models.CharField(blank=True, default='', max_length=64)),
                ('job_number', models.CharField(blank=True, default='', max_length=64)),
                ('task_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('machine_name', models.CharField(blank=True, default='', max_length=200)),
                ('designer', models.CharField(default='Dharmesh Joshi', max_length=150)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('target_date', models.CharField(blank=True, default='', max_length=50)),
                ('due_date', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.CharField(default='high', max_length=30)),
                ('estimated_hours', models.FloatField(default=16)),
                ('actual_hours', models.FloatField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
