# Generated by Django 5.2.17 on 2026-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_designtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyDrawing',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('design_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('project_id', models.CharField(blank=True, default='', max_length=64)),
                ('job_number', models.CharField(blank=True, default='', max_length=64)),
                ('assembly_number', models.CharField(max_length=100)),
                ('assembly_title', models.CharField(max_length=200)),
                ('sub_assembly_code', models.CharField(blank=True, default='', max_length=100)),
                ('parent_assembly_number', models.CharField(blank=True, default='', max_length=100)),
                ('revision_number', models.CharField(default='REV-00', max_length=30)),
                ('file_format', models.CharField(default='DWG', max_length=30)),
                ('file_size', models.CharField(default='5.0 MB', max_length=50)),
                ('file_url', models.CharField(blank=True, default='#', max_length=255)),
                ('linked_bom_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('drawn_by', models.CharField(blank=True, default='', max_length=150)),
                ('approved_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
