# Generated by Django 5.2.17 on 2026-09-30 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_assemblydrawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='access_permission',
            field=models.CharField(blank=True, default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='document_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='file_size',
            field=models.CharField(blank=True, default='5.2 MB', max_length=50),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='revision',
            field=models.CharField(blank=True, default='REV-00', max_length=30),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='upload_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='uploaded_by',
            field=models.CharField(blank=True, default='Dharmesh Joshi', max_length=150),
        ),
        migrations.AddField(
            model_name='technicaldocumentitem',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='category',
            field=models.CharField(blank=True, default='Calculation', max_length=50),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='created_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='design_job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='doc_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='file_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicaldocumentitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
