# Generated by Django 5.2.17 on 2026-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_technicaldocumentitem_access_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designjob',
            name='approval_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designjob',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='designjob',
            name='approved_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='designjob',
            name='disapproved_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='designjob',
            name='disapproved_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='designjob',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
