# Generated by Django 4.2.22 on 2026-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_designjob_approval_notes_designjob_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomheader',
            options={'verbose_name': 'Bill of Materials (BOM)', 'verbose_name_plural': 'Bills of Materials (BOM)'},
        ),
        migrations.AlterModelOptions(
            name='design3dmodel',
            options={'verbose_name': '3D Design Model', 'verbose_name_plural': '3D Design Models'},
        ),
        migrations.AlterModelOptions(
            name='drawing2d',
            options={'verbose_name': '2D Drawing', 'verbose_name_plural': '2D Drawings'},
        ),
    ]
