# Generated by Django 4.2.30 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_materialrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='other_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='bom_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='job_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='msme_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='msme_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
