from django.core.management.base import BaseCommand
from apps.crm.models import (
    Customer,
    Contact,
    Lead,
    Enquiry,
    Opportunity,
    FollowUp,
    SiteVisit,
    Exhibition,
    Quotation,
    CustomerPO,
    SalesOrder,
)


class Command(BaseCommand):
    help = 'Seeds initial CRM & Sales data (Customers, Leads, Enquiries, Opportunities, Quotations, CPO, Sales Orders)'

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE('Starting Phase 2 CRM Data Seeding...'))

        # 1. Customers
        customers_data = [
            {
                'id': 'CUST-2026-0001',
                'customer_code': 'CUST-001',
                'customer_type': 'company',
                'company_name': 'Gujarat Alkalies & Chemicals Ltd. (GACL)',
                'industry': 'Chemical & Alkali Manufacturing',
                'gstin': '24AAACG1234P1Z1',
                'pan': 'AAACG1234P',
                'website': 'https://www.gacl.com',
                'contact_person': 'Harish Trivedi',
                'designation': 'General Manager - Projects & Capex',
                'mobile': '+91 98251 99881',
                'email': 'harish.trivedi@gacl.co.in',
                'whatsapp': '+91 98251 99881',
                'billing_address': 'P.O. Petrochemicals, Ranoli, Vadodara',
                'shipping_address': 'GACL Complex, Dahej Plant, Bharuch',
                'city': 'Vadodara',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '391346',
                'payment_terms': '30% Advance, 60% against Proforma, 10% after Commissioning',
                'credit_limit': 25000000,
                'currency': 'INR (₹)',
                'category': 'platinum',
                'assigned_sales_person': 'Pravin Patel',
                'created_date': '2025-01-15',
            },
            {
                'id': 'CUST-2026-0002',
                'customer_code': 'CUST-002',
                'customer_type': 'company',
                'company_name': 'Torrent Pharmaceuticals Ltd.',
                'industry': 'Pharmaceuticals & Formulation',
                'gstin': '24AAACT5566K1Z9',
                'pan': 'AAACT5566K',
                'website': 'https://www.torrentpharma.com',
                'contact_person': 'Sanjay Deshmukh',
                'designation': 'Head of Engineering & Procurement',
                'mobile': '+91 98252 44332',
                'email': 'sanjay.d@torrentpharma.com',
                'whatsapp': '+91 98252 44332',
                'billing_address': 'Torrent House, Off Ashram Road, Ahmedabad',
                'shipping_address': 'Torrent Indrad Plant, Kadi, Mehsana',
                'city': 'Ahmedabad',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '380009',
                'payment_terms': '20% Advance, 70% against Dispatch, 10% against FAT & DQ/IQ/OQ Handover',
                'credit_limit': 30000000,
                'currency': 'INR (₹)',
                'category': 'platinum',
                'assigned_sales_person': 'Amit Sharma',
                'created_date': '2025-03-20',
            },
            {
                'id': 'CUST-2026-0003',
                'customer_code': 'CUST-003',
                'customer_type': 'company',
                'company_name': 'Zydus Lifesciences Ltd.',
                'industry': 'Pharma & Biotech',
                'gstin': '24AAACZ9988J1Z5',
                'pan': 'AAACZ9988J',
                'website': 'https://www.zyduslife.com',
                'contact_person': 'Manoj Mehta',
                'designation': 'Sr. Manager - Technical Services',
                'mobile': '+91 98253 77889',
                'email': 'manoj.mehta@zyduslife.com',
                'whatsapp': '+91 98253 77889',
                'billing_address': 'Zydus Corporate Park, Scheme 63, Ahmedabad',
                'shipping_address': 'Zydus SEZ Matoda, Ahmedabad',
                'city': 'Ahmedabad',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '382210',
                'payment_terms': '30% Advance, 70% against Dispatch',
                'credit_limit': 20000000,
                'currency': 'INR (₹)',
                'category': 'gold',
                'assigned_sales_person': 'Amit Sharma',
                'created_date': '2025-05-10',
            },
            {
                'id': 'CUST-2026-0004',
                'customer_code': 'CUST-004',
                'customer_type': 'company',
                'company_name': 'Atul Ltd.',
                'industry': 'Speciality Chemicals',
                'gstin': '24AAACA1122B1Z3',
                'pan': 'AAACA1122B',
                'website': 'https://www.atul.co.in',
                'contact_person': 'Paresh Gandhi',
                'designation': 'Sr. Manager - Technical Purchase',
                'mobile': '+91 98255 66778',
                'email': 'paresh.gandhi@atul.co.in',
                'whatsapp': '+91 98255 66778',
                'billing_address': 'Atul Complex, Valsad District',
                'shipping_address': 'Atul Complex, Valsad District',
                'city': 'Valsad',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '396020',
                'payment_terms': '20% Advance, 70% against Proforma, 10% against Performance Guarantee',
                'credit_limit': 20000000,
                'currency': 'INR (₹)',
                'category': 'gold',
                'assigned_sales_person': 'Amit Sharma',
                'created_date': '2025-07-15',
            },
        ]
        for c in customers_data:
            Customer.objects.update_or_create(id=c['id'], defaults=c)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(customers_data)} Customers seeded.'))

        # 2. Leads
        leads_data = [
            {
                'id': 'LEAD-2026-0101',
                'lead_no': 'LEAD-2026-0101',
                'company_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'industry': 'Chemical',
                'website': 'https://www.gacl.com',
                'gstin': '24AAACG1234P1Z1',
                'address': 'Ranoli Industrial Area',
                'city': 'Vadodara',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '391346',
                'contact_person': 'Harish Trivedi',
                'designation': 'General Manager - Projects',
                'mobile': '+91 98251 99881',
                'email': 'harish.trivedi@gacl.co.in',
                'whatsapp': '+91 98251 99881',
                'product_name': 'Heavy SS 316L Chemical Reactor Vessel (10 KL)',
                'machine_type': 'Chemical Pressure Vessel / Reactor',
                'quantity': 1,
                'capacity': '10,000 Litres',
                'application': 'Corrosive Acid Formulation with Anchor Agitation',
                'requirement_description': 'Design, fabrication and hydro testing of 10 KL SS 316L Limpet Jacketed Reactor, 8 Bar Design Pressure, ASME Sec VIII Div 1 compliant.',
                'expected_delivery': '2026-10-15',
                'budget': 5000000,
                'priority': 'high',
                'source': 'existing_customer',
                'assigned_sales_person_id': 'EMP-003',
                'assigned_sales_person_name': 'Pravin Patel',
                'status': 'won',
                'next_follow_up_date': '2026-09-30',
                'created_date': '2026-08-01',
                'converted_customer_id': 'CUST-2026-0001',
                'converted_enquiry_id': 'ENQ-2026-0061',
                'converted_opportunity_id': 'OPP-2026-0048',
            },
            {
                'id': 'LEAD-2026-0102',
                'lead_no': 'LEAD-2026-0102',
                'company_name': 'Torrent Pharmaceuticals Ltd.',
                'industry': 'Pharmaceuticals',
                'address': 'Indrad Industrial Estate',
                'city': 'Mehsana',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '382715',
                'contact_person': 'Sanjay Deshmukh',
                'designation': 'Head of Engineering',
                'mobile': '+91 98252 44332',
                'email': 'sanjay.d@torrentpharma.com',
                'product_name': 'Automatic Fluid Bed Dryer Machine (FBD-150)',
                'machine_type': 'Pharma Drying Equipment',
                'quantity': 2,
                'capacity': '150 Kg/Batch',
                'application': 'Granulation & Pellet Drying in Sterile Cleanroom',
                'requirement_description': 'Supply of 2 units of PLC SCADA automated FBD-150 with DQ/IQ/OQ documentation, SS 316L mirror polished contact parts.',
                'expected_delivery': '2026-09-30',
                'budget': 6500000,
                'priority': 'urgent',
                'source': 'referral',
                'assigned_sales_person_id': 'EMP-007',
                'assigned_sales_person_name': 'Amit Sharma',
                'status': 'won',
                'created_date': '2026-07-02',
                'converted_customer_id': 'CUST-2026-0002',
            },
            {
                'id': 'LEAD-2026-0103',
                'lead_no': 'LEAD-2026-0103',
                'company_name': 'Atul Ltd. (Aromatics Division)',
                'industry': 'Speciality Chemicals & Dyestuff',
                'address': 'Atul Complex, Valsad District',
                'city': 'Valsad',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '396020',
                'contact_person': 'Paresh Gandhi',
                'designation': 'Sr. Manager - Technical Purchase',
                'mobile': '+91 98255 66778',
                'email': 'paresh.gandhi@atul.co.in',
                'product_name': 'Hastelloy C-276 Clad Distillation Column (24 Mtr Height)',
                'machine_type': 'Heavy Distillation Column',
                'quantity': 1,
                'capacity': '2400mm Dia x 24000mm Length',
                'application': 'High Temperature Acidic Solvent Stripping',
                'requirement_description': 'Custom fabrication of heavy distillation column with bubble cap trays, Hastelloy internal cladding and full radiography weld joints.',
                'expected_delivery': '2026-12-15',
                'budget': 14500000,
                'priority': 'high',
                'source': 'exhibition',
                'assigned_sales_person_id': 'EMP-007',
                'assigned_sales_person_name': 'Amit Sharma',
                'status': 'quotation_sent',
                'next_follow_up_date': '2026-09-24',
                'created_date': '2026-09-05',
            },
            {
                'id': 'LEAD-2026-0104',
                'lead_no': 'LEAD-2026-0104',
                'company_name': 'Aarti Industries Ltd.',
                'industry': 'Chemicals & Agrochemicals',
                'address': 'GIDC Jhagadia, Bharuch',
                'city': 'Bharuch',
                'state': 'Gujarat',
                'country': 'India',
                'pincode': '393110',
                'contact_person': 'Rajeev Singhal',
                'designation': 'Project Lead',
                'mobile': '+91 98256 11224',
                'email': 'rajeev.singhal@aarti-industries.com',
                'product_name': 'SS 304 High Pressure Autoclave (5000 Litres, 25 Bar)',
                'machine_type': 'High Pressure Autoclave',
                'quantity': 1,
                'capacity': '5000 Litres',
                'application': 'Hydrogenation & High Pressure Catalytic Reactions',
                'requirement_description': 'Supply of heavy forged flange autoclave with magnetic drive agitator, explosion-proof control panel, and CE certification.',
                'expected_delivery': '2026-11-30',
                'budget': 9200000,
                'priority': 'urgent',
                'source': 'website',
                'assigned_sales_person_id': 'EMP-003',
                'assigned_sales_person_name': 'Pravin Patel',
                'status': 'requirement_received',
                'next_follow_up_date': '2026-09-25',
                'created_date': '2026-09-12',
            },
        ]
        for l in leads_data:
            Lead.objects.update_or_create(id=l['id'], defaults=l)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(leads_data)} Leads seeded.'))

        # 3. Enquiries
        enquiries_data = [
            {
                'id': 'ENQ-2026-0061',
                'enquiry_no': 'ENQ-2026-0061',
                'lead_id': 'LEAD-2026-0101',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'enquiry_date': '2026-08-02',
                'requirement': '10 KL SS 316L Limpet Jacketed Reactor Vessel with Flameproof Drive',
                'machine_product': 'Chemical Reactor Vessel',
                'quantity': 1,
                'specification': 'Capacity: 10,000 L, Pressure: 8 Bar Shell / 6 Bar Jacket, SS 316L Contact Parts',
                'expected_delivery': '2026-10-15',
                'assigned_person_id': 'EMP-003',
                'assigned_person_name': 'Pravin Patel',
                'status': 'converted',
                'quotation_id': 'QT-2026-0118',
            },
            {
                'id': 'ENQ-2026-0062',
                'enquiry_no': 'ENQ-2026-0062',
                'lead_id': 'LEAD-2026-0103',
                'customer_id': 'CUST-2026-0004',
                'customer_name': 'Atul Ltd.',
                'enquiry_date': '2026-09-06',
                'requirement': 'Hastelloy C-276 Clad Heavy Distillation Column (24 Mtr Height)',
                'machine_product': 'Distillation Column',
                'quantity': 1,
                'specification': 'Dia: 2400mm, Height: 24,000mm, Shell: SA 516 Gr 70 + 3mm Hastelloy Clad',
                'expected_delivery': '2026-12-15',
                'assigned_person_id': 'EMP-007',
                'assigned_person_name': 'Amit Sharma',
                'status': 'quotation_ready',
                'quotation_id': 'QT-2026-0131',
            },
        ]
        for e in enquiries_data:
            Enquiry.objects.update_or_create(id=e['id'], defaults=e)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(enquiries_data)} Enquiries seeded.'))

        # 4. Opportunities
        opp_data = [
            {
                'id': 'OPP-2026-0048',
                'opportunity_no': 'OPP-2026-0048',
                'lead_id': 'LEAD-2026-0101',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'machine_product': 'Heavy SS 316L Chemical Reactor Vessel (10 KL)',
                'estimated_value': 4850000,
                'expected_closing_date': '2026-08-08',
                'sales_person_id': 'EMP-003',
                'sales_person_name': 'Pravin Patel',
                'probability': 100,
                'stage': 'won',
                'remarks': 'Customer PO Received: PO/GACL/FAB/2026/089',
                'quotation_id': 'QT-2026-0118',
            },
            {
                'id': 'OPP-2026-0049',
                'opportunity_no': 'OPP-2026-0049',
                'lead_id': 'LEAD-2026-0103',
                'customer_id': 'CUST-2026-0004',
                'customer_name': 'Atul Ltd.',
                'machine_product': 'Hastelloy C-276 Clad Distillation Column (24 Mtr)',
                'estimated_value': 13800000,
                'expected_closing_date': '2026-09-30',
                'sales_person_id': 'EMP-007',
                'sales_person_name': 'Amit Sharma',
                'probability': 75,
                'stage': 'negotiation',
                'remarks': 'Final commercial review scheduled with VP Projects',
                'quotation_id': 'QT-2026-0131',
            },
        ]
        for opp in opp_data:
            Opportunity.objects.update_or_create(id=opp['id'], defaults=opp)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(opp_data)} Opportunities seeded.'))

        # 5. FollowUps
        followups_data = [
            {
                'id': 'FLW-2026-0031',
                'follow_up_no': 'FLW-2026-0031',
                'lead_or_customer_id': 'LEAD-2026-0105',
                'lead_or_customer_name': 'Cadila Pharmaceuticals (Kishore Dave)',
                'entity_type': 'lead',
                'type': 'meeting',
                'assigned_to_id': 'EMP-007',
                'assigned_to_name': 'Amit Sharma',
                'date': '2026-09-23',
                'time': '02:30 PM',
                'priority': 'high',
                'purpose': 'Technical Discussion on cGMP Multi-Mill specification & delivery timeline',
                'notes': 'Customer requires FAT clearance within 45 days of PO.',
                'status': 'pending',
            },
            {
                'id': 'FLW-2026-0032',
                'follow_up_no': 'FLW-2026-0032',
                'lead_or_customer_id': 'LEAD-2026-0103',
                'lead_or_customer_name': 'Atul Ltd. (Paresh Gandhi)',
                'entity_type': 'lead',
                'type': 'call',
                'assigned_to_id': 'EMP-007',
                'assigned_to_name': 'Amit Sharma',
                'date': '2026-09-23',
                'time': '04:00 PM',
                'priority': 'urgent',
                'purpose': 'Commercial Negotiation on QT-2026-0131 for Distillation Column',
                'notes': 'Follow-up regarding 3% cash discount request and L/C payment term clause.',
                'status': 'pending',
            },
        ]
        for f in followups_data:
            FollowUp.objects.update_or_create(id=f['id'], defaults=f)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(followups_data)} FollowUps seeded.'))

        # 6. Site Visits
        visits_data = [
            {
                'id': 'VST-2026-0031',
                'visit_no': 'VST-2026-0031',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'contact_person': 'Harish Trivedi',
                'contact_mobile': '+91 98251 99881',
                'visit_date': '2026-09-15',
                'location': 'GACL Complex, Dahej Plant 2',
                'employee_id': 'EMP-003',
                'employee_name': 'Pravin Patel',
                'purpose': 'Site Foundation & Piping tie-in verification for 10 KL Reactor Vessel',
                'discussion_notes': 'Inspected concrete foundation pad (Bay 4), verified civil anchor bolt layout, and checked nozzle tie-in coordinates.',
                'requirement_details': 'Customer requested 2 additional SS 316 sampling valves on the bottom outlet line.',
                'outcome': 'positive',
                'next_action': 'Incorporate revised bottom nozzle orientation into BOM-CRV-10K-R2.',
                'next_follow_up_date': '2026-09-28',
            },
        ]
        for v in visits_data:
            SiteVisit.objects.update_or_create(id=v['id'], defaults=v)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(visits_data)} SiteVisits seeded.'))

        # 7. Quotations with Revisions
        quotations_data = [
            {
                'id': 'QT-2026-0118',
                'quotation_number': 'QT-2026-0118',
                'current_revision': 'Rev-01',
                'date': '2026-08-04',
                'valid_until': '2026-09-04',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'contact_person': 'Harish Trivedi',
                'contact_email': 'harish.trivedi@gacl.co.in',
                'contact_mobile': '+91 98251 99881',
                'enquiry_id': 'ENQ-2026-0061',
                'opportunity_id': 'OPP-2026-0048',
                'sales_person_id': 'EMP-003',
                'sales_person_name': 'Pravin Patel',
                'notes': 'ASME Sec VIII Div 1 Reactor',
                'revisions': [
                    {
                        'revisionNumber': 'Rev-00',
                        'date': '2026-08-04',
                        'preparedBy': 'Amit Sharma',
                        'approvedBy': 'Pravin Patel',
                        'items': [
                            {
                                'id': 'qi-1',
                                'productName': 'Heavy SS 316L Chemical Reactor Vessel (10 KL)',
                                'description': 'Shell: 8mm SS 316L, Dish Ends: 10mm SS 316L Torispherical, Jacket: Dimple SS 304, Agitator: 15 HP Flameproof Anchor type.',
                                'quantity': 1,
                                'unit': 'Set',
                                'rate': 4200000,
                                'discountPercent': 0,
                                'taxPercent': 18,
                                'amount': 4956000,
                            }
                        ],
                        'subTotal': 4200000,
                        'discountAmount': 0,
                        'taxAmount': 756000,
                        'grandTotal': 4956000,
                        'technicalSpecs': 'Design Code: ASME Sec VIII Div 1. Hydro test pressure: 12 Bar. Design Temp: 180°C.',
                        'scopeOfSupply': 'Supply of complete reactor, agitator with mechanical seal, motor, gearbox, mounting stool and sight glass.',
                        'exclusions': 'Civil foundation, external interconnecting piping, insulation cladding at site.',
                        'paymentTerms': '30% Advance, 60% against Proforma Invoice before dispatch, 10% after erection & commissioning.',
                        'deliveryTime': '10 to 12 Weeks from approved GA drawing and advance payment.',
                        'warranty': '18 Months from dispatch or 12 Months from commissioning, whichever is earlier.',
                        'termsAndConditions': 'Prices are Ex-Works Makarpura, Vadodara. Freight & Transit Insurance extra at actuals.',
                        'status': 'sent',
                    },
                    {
                        'revisionNumber': 'Rev-01',
                        'date': '2026-08-06',
                        'preparedBy': 'Pravin Patel',
                        'approvedBy': 'Rajesh Patel',
                        'items': [
                            {
                                'id': 'qi-1',
                                'productName': 'Heavy SS 316L Chemical Reactor Vessel (10 KL) [Discounted Commercial]',
                                'description': 'Shell: 8mm SS 316L, Dish Ends: 10mm SS 316L Torispherical, Jacket: Dimple SS 304, Agitator: 15 HP Flameproof Anchor type with Dual Mechanical Seal.',
                                'quantity': 1,
                                'unit': 'Set',
                                'rate': 4110169,
                                'discountPercent': 0,
                                'taxPercent': 18,
                                'amount': 4850000,
                            }
                        ],
                        'subTotal': 4110169,
                        'discountAmount': 0,
                        'taxAmount': 739831,
                        'grandTotal': 4850000,
                        'technicalSpecs': 'Design Code: ASME Sec VIII Div 1. Hydro test pressure: 12.5 Bar. Design Temp: 180°C.',
                        'scopeOfSupply': 'Supply of complete reactor, dual mechanical seal with thermosiphon pot, 15 HP ABB IE3 Flameproof motor, gearbox.',
                        'exclusions': 'Civil foundation, external interconnecting piping, insulation cladding.',
                        'paymentTerms': '30% Advance, 60% against Proforma, 10% after Commissioning.',
                        'deliveryTime': '8 to 10 Weeks from approved GA drawing.',
                        'warranty': '18 Months from dispatch.',
                        'termsAndConditions': 'Prices Ex-Works Vadodara. Freight charged extra.',
                        'status': 'accepted',
                    },
                ],
            },
        ]
        for q in quotations_data:
            Quotation.objects.update_or_create(id=q['id'], defaults=q)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(quotations_data)} Quotations seeded.'))

        # 8. Customer POs
        pos_data = [
            {
                'id': 'CPO-2026-0041',
                'po_number': 'PO/GACL/FAB/2026/089',
                'internal_cpo_no': 'CPO-2026-0041',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'quotation_id': 'QT-2026-0118',
                'quotation_number': 'QT-2026-0118 (Rev-01)',
                'po_date': '2026-08-08',
                'received_date': '2026-08-08',
                'delivery_date': '2026-10-15',
                'po_value': 4850000,
                'scope_of_work': 'Supply of 10 KL SS 316L Chemical Reactor Vessel',
                'payment_terms': '30% Advance, 60% ag. Proforma, 10% ag. Handover',
                'status': 'converted_to_so',
                'converted_so_id': 'SO-2026-0042',
            },
        ]
        for po in pos_data:
            CustomerPO.objects.update_or_create(id=po['id'], defaults=po)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(pos_data)} Customer POs seeded.'))

        # 9. Sales Orders
        so_data = [
            {
                'id': 'SO-2026-0042',
                'sales_order_number': 'SO-2026-0042',
                'customer_po_id': 'CPO-2026-0041',
                'customer_po_number': 'PO/GACL/FAB/2026/089',
                'quotation_id': 'QT-2026-0118',
                'quotation_number': 'QT-2026-0118',
                'customer_id': 'CUST-2026-0001',
                'customer_name': 'Gujarat Alkalies & Chemicals Ltd.',
                'order_date': '2026-08-09',
                'target_delivery_date': '2026-10-15',
                'items': [
                    {
                        'productName': 'Heavy SS 316L Chemical Reactor Vessel (10 KL)',
                        'description': 'Complete Reactor with Limpet Jacket and Agitator',
                        'quantity': 1,
                        'unit': 'Set',
                        'rate': 4110169,
                        'amount': 4110169,
                    }
                ],
                'total_amount': 4110169,
                'tax_amount': 739831,
                'grand_total': 4850000,
                'payment_terms': '30% Advance, 60% against Proforma, 10% after Commissioning',
                'billing_address': 'P.O. Petrochemicals, Ranoli, Vadodara',
                'shipping_address': 'GACL Complex, Dahej Plant, Bharuch',
                'status': 'confirmed',
                'project_id': 'PRJ-2026-0042',
                'created_by': 'Pravin Patel',
                'approved_by': 'Rajesh Patel',
            },
        ]
        for so in so_data:
            SalesOrder.objects.update_or_create(id=so['id'], defaults=so)
        self.stdout.write(self.style.SUCCESS(f'[OK] {len(so_data)} Sales Orders seeded.'))
        self.stdout.write(self.style.SUCCESS('Done: Phase 2 CRM Seeding Complete!'))
