# Generated by Django 4.2.30 on 2026-10-08 12:39

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=apps.authentication.models.generate_user_id, max_length=64, primary_key=True, serialize=False),
        ),
    ]
